# Generated by Django 5.1.15 on 2026-10-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('INVESTMENT', 'Investment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(choices=[('Food', 'Food & Dining'), ('Transport', 'Transport & Fuel'), ('Shopping', 'Shopping'), ('Utilities', 'Bills & Utilities'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Bills', 'Bills'), ('Salary', 'Salary'), ('Investment', 'Investment'), ('Other', 'Other')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Net Banking', 'Net Banking'), ('Other', 'Other')], default='UPI', max_length=30)),
                ('transaction_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
