# Generated by Django 5.1.15 on 2026-10-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings Account'), ('Current', 'Current Account'), ('Salary', 'Salary Account'), ('Credit Card', 'Credit Card'), ('Investment', 'Investment Account')], default='Savings', max_length=30)),
                ('account_number', models.CharField(max_length=34)),
                ('masked_account_number', models.CharField(blank=True, max_length=34)),
                ('bank_name', models.CharField(default='Finora Bank', max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
