# Generated by Django 5.1.15 on 2026-10-05 13:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('month', models.IntegerField(default=10)),
                ('year', models.IntegerField(default=2026)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-year', '-month', 'category'],
            },
        ),
    ]
