# Generated by Django 5.1.15 on 2026-10-05 13:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('Stocks', 'Stocks'), ('Mutual Funds', 'Mutual Funds'), ('Gold', 'Gold'), ('Fixed Deposits', 'Fixed Deposits'), ('Cryptocurrency', 'Cryptocurrency'), ('ETF', 'ETF')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('average_buy_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'investments',
                'ordering': ['-created_at'],
            },
        ),
    ]
